spring:
  application:
    name: library-web
  datasource:
    url: "jdbc:postgresql://localhost:5432/d_library"
    username: lib01
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  key: ${JWT_KEY}
  access-token-expiration: 3600000
  refresh-token-expiration: 1296000000